import type {
  Advisor,
  DocumentItem,
  ProfileAnalysis,
  SchoolRecommendation,
  StudentProfile,
  WorkflowRun,
} from "../types/domain";

export const sampleProfile: StudentProfile = {
  id: "profile_demo",
  name: "张三",
  university: "厦门大学",
  major: "计算机科学与技术",
  rank_percent: 8,
  gpa: 3.82,
  english_score: "CET-6 523",
  target_degree: "master",
  risk_preference: "balanced",
  research_interests: ["机器学习", "智能体系统"],
  projects: ["多智能体保研助手", "课程推荐系统"],
  competitions: ["蓝桥杯省级奖项"],
  publications: ["A类会议论文二作 1 篇"],
  target_regions: ["上海", "北京"],
  preferred_schools: ["上海交通大学", "浙江大学"],
  notes: "希望申请人工智能系统与智能体方向。",
  updated_at: new Date().toISOString(),
};

export const sampleProfileAnalysis: ProfileAnalysis = {
  overall_score: 86,
  academic_score: 88,
  research_score: 84,
  project_score: 82,
  competition_score: 74,
  language_score: 82,
  strengths: ["排名和绩点表现较强，具备冲击强校的基础。", "项目方向与智能体系统相关，便于形成清晰的申请主线。"],
  weaknesses: ["科研成果还不够多，需要把已有论文和项目价值讲得更具体。"],
  suggestions: ["突出论文和项目中的个人贡献。", "提前准备材料与面试表达。"],
  summary: "当前背景适合采用冲刺、稳妥、保底并行推进的申请策略。",
};

export const sampleRecommendations: SchoolRecommendation[] = [
  {
    school_name: "上海交通大学",
    program_name: "计算机夏令营",
    level: "challenge",
    match_score: 84,
    reasons: ["排名基础较强。", "研究方向与目标实验室匹配度较高。"],
    risks: ["机考和项目追问压力较大。"],
    todo: ["优先整理项目亮点。", "提前准备导师联系材料。"],
    evidence: [{ title: "上海交通大学 / 人工智能学院 / camp2026", url: "https://example.edu/sjtu-camp" }],
    materials: ["个人简历", "成绩单", "排名证明"],
    exam_format: ["机考", "专业面试"],
    deadline: "6月中旬",
    notice_url: "https://example.edu/sjtu-camp",
    agent_insight: "适合作为冲刺目标，重点补强机考和项目表达。",
  },
  {
    school_name: "浙江大学",
    program_name: "计算机科学项目",
    level: "stable",
    match_score: 79,
    reasons: ["院校方向匹配度较高。", "稳妥梯度合理。"],
    risks: ["需要把科研动机表达得更完整。"],
    todo: ["完善个人陈述。", "补足材料细节。"],
    evidence: [],
    materials: [],
    exam_format: [],
    deadline: "",
    notice_url: "",
    agent_insight: "适合稳妥推进，重点讲清研究兴趣和项目逻辑。",
  },
  {
    school_name: "山东大学",
    program_name: "前沿交叉科学青岛研究院",
    level: "safe",
    match_score: 74,
    reasons: ["保底梯度更合理。", "已有通知线索便于尽快准备。"],
    risks: ["仍需确认具体导师和考核方式。"],
    todo: ["尽早核对通知。", "确认截止时间和报名材料。"],
    evidence: [{ title: "山东大学 / 前沿交叉科学青岛研究院 / camp2026", url: "https://example.edu/sdu-camp" }],
    materials: [],
    exam_format: [],
    deadline: "2026-06-29T00:00:00+08:00",
    notice_url: "https://example.edu/sdu-camp",
    agent_insight: "更适合作为保底院校，重点是用现有通知快速完成准备闭环。",
  },
];

export const sampleDocuments: DocumentItem[] = [
  {
    id: "doc_notice",
    title: "上海交通大学计算机夏令营通知",
    doc_type: "notice",
    source_type: "sample",
    content: "需要准备个人简历、成绩单、排名证明、科研陈述，可能包含机考或专业面试。",
    source: "sample",
    keywords: ["上海交通大学", "个人简历", "机考"],
    chunks: [],
    extracted: { materials: ["个人简历", "成绩单", "排名证明"], exam_format: ["机考", "专业面试"] },
    created_at: new Date().toISOString(),
  },
  {
    id: "doc_advisor",
    title: "王老师主页摘要",
    doc_type: "advisor",
    source_type: "sample",
    content: "研究方向包括机器学习系统、大模型应用和可信人工智能。",
    source: "sample",
    keywords: ["大模型应用", "智能体系统", "机器学习"],
    chunks: [],
    extracted: { name: "王老师", research_areas: ["大模型应用", "机器学习系统"] },
    created_at: new Date().toISOString(),
  },
];

export const sampleAdvisors: Advisor[] = [
  {
    id: "advisor_wang",
    name: "王老师",
    university: "上海交通大学",
    department: "计算机科学与工程系",
    research_areas: ["机器学习", "智能体系统", "大模型应用"],
    homepage: "https://example.edu/wang",
    summary: "关注智能体系统和应用机器学习，适合有工程项目经验的学生。",
    representative_works: ["面向可信应用的智能系统研究"],
    suitable_background: "适合有机器学习项目、系统开发或科研训练经历的学生。",
    source_document_id: "doc_advisor",
  },
  {
    id: "advisor_chen",
    name: "陈老师",
    university: "浙江大学",
    department: "计算机科学与技术学院",
    research_areas: ["数据库", "信息检索", "检索增强问答"],
    homepage: "https://example.edu/chen",
    summary: "关注检索系统与数据管理，适合对搜索、问答和数据库感兴趣的学生。",
    representative_works: ["面向问答场景的数据管理研究"],
    suitable_background: "适合有数据库、搜索系统或问答项目经历的学生。",
    source_document_id: "",
  },
];

export const sampleWorkflow: WorkflowRun = {
  id: "workflow_demo",
  workflow_type: "planning",
  status: "completed",
  created_at: new Date().toISOString(),
  final_result: "已生成院校梯度、准备节奏和导师联系建议。",
  steps: [
    {
      name: "分析学生画像",
      status: "completed",
      agent_result: {
        id: "agent_profile",
        agent_name: "ProfileAgent",
        input_summary: "专业排名前8%，方向为机器学习和智能体系统。",
        output: "当前背景适合申请人工智能系统相关项目。",
        references: [],
        created_at: new Date().toISOString(),
      },
    },
    {
      name: "生成申请节奏",
      status: "completed",
      agent_result: {
        id: "agent_planner",
        agent_name: "PlannerAgent",
        input_summary: "结合推荐院校与截止时间。",
        output: "先准备材料，再联系导师，最后集中进行面试练习。",
        references: ["上海交通大学计算机夏令营通知"],
        created_at: new Date().toISOString(),
      },
    },
  ],
};
